### ISSUE TITLE
Display text descriptions for codes

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#316]
As a user,
I want to see the text descriptions for the cryptic historical HMDA values

A/C:
- Address codes in Edit descriptions and Line level details

Tasks:
- [x] Identify alternative approaches: 
 - ~~Trigger a page/site-wide toggle between displaying codes or descriptions~~
 - ~~Trigger a page/site-wide toggle between displaying codes, or code and descriptions~~
 - ~~Add a tooltip to each code~~
 - Display a list of the lookup values relevant to the current page in a modal window for easy reference
- [x] Implement selected approach @doelleri

**Comment by doelleri** [comment]
Can someone give an example of a "cryptic historical HMDA value" and the text description for it?
Is one of the alternative approaches a preferred approach and what approach are they alternatives to?

**Comment by poorgeek** [comment]
An example would be the S020 edit that checks the agencyCode. Currently the report displays the following:

![hmda_pilot___cfpb](https://cloud.githubusercontent.com/assets/489299/7183966/da0bbbcc-e417-11e4-872a-e86e7ede7a6d.jpg)

In this image we list the label as "Agency Code", but list the submitted value as 6. The user may not know which agency is represented by the the "6".

**Comment by doelleri** [comment]
This might be a slippery slope. For example,
![image](https://cloud.githubusercontent.com/assets/695452/7184407/17a3a676-e42b-11e4-9e3f-30c973077d5b.png)
There are text labels "action code of 5" and "Loans where Action Taken = 5" that will not be easy to dynamically modify based on what we currently have.

**Comment by poorgeek** [comment]
Good point. How far of a reach should this formatting go? Is it only to the field labels in the tables or should it also apply to the edit explanations that are displayed at the top of the detail views and the edit descriptions shown in the summary tables? Knowing the answer to that would also inform where any sort of toggle would need to go in the UI since this would be a global toggle, applicable across views, rather than just something that should be flipped on/off for the current detail table.

**Comment by poorgeek** [comment]
Just talked to @debseidner about a 4th option for handling this. We could display a list of the relevant lookup values in a modal (added to list above). This would allow for a user to see all of possible values for properties rather than just toggling a single value from its submitted value to a human-readable version. This also solves the issue with edit explanations and descriptions where it would be very difficult to translate those into something human-readable. Instead, the user could look at the lookup values in the modal as a reference.

**Comment by ericspry** [comment]
I like option 4. I think this gets at the heart of the issue (quick reference for values) without going too crazy.
