### ISSUE TITLE
Application automatically deletes local data storage created to improve the performance of large test sets

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#327]
As a user, 
I want the application to automatically delete local data when it is no longer needed

A/C:
- Local storage is automatically deleted when the user reaches the (1) Select file & validate page, or the (5) Validation Summary page

Tasks For Story:

- [x] Update UI to call engine hooks for destroying the database

**Comment by pkaplan** [comment]
Should we incorporate deleting the temp file into an Exit button on the last page which also closes the browser window?

**Comment by poorgeek** [comment]
I had a similar conversation with @awolfe76 yesterday. In my opinion, deleting the IndexedDB negates one of the useful elements of the IndexedDB feature and that is persistence between sessions. The census data is open data and isn't changing at odd times so there really is no need to delete unless at the user's own request which we are handling from the home page. 

As part of this discussion, I did realize that the opt-in checkbox on the home page is missing the feature that it should be setting its checked state based on whether the census data has already been downloaded or not. By adding that, the user can see if they have the file already installed when they come back to the home page. It's on my list to add a new issue for this item today.

If we want a separate button on the Validation Summary view to close the current tab/window thus ending the session, then that should be a new issue. I do think it would be wrong to imply that by clicking that button that the user wants to wipe the census data from their local IndexedDB.

**Comment by LinuxBozo** [comment]
@poorgeek not really necessary to check for "already downloaded", since the data gets loaded each time the box is checked regardless. This is because it uses a single IndexedDB for the data. Since you could possibly do a edit run on 2013 in one session, and the next decided to do 2014, the data could be (and probably will be) different between years, so the db gets reset with the appropriate data every session when the box is checked.

**Comment by poorgeek** [comment]
I thought that for the purpose of the pilot the census data was the same between filing years since the census only occurs every 10 years? However if it does change between filing years, then in your scenario, what happens if the box isn't checked between sessions? Does "stale" census data hang around until the user clicks the checkbox or the "clear" button that's part of this feature?

**Comment by LinuxBozo** [comment]
The census data includes MSA/MD, which actually have changed between years, hence the need for that data to be produced/loaded for the 2014 "dirty data" files.

If the box is not checked when the user clicks to start validation, the old data is completely wiped (if it exists). The scenario where data is still there is an edge case basically. It's there in the browser if the user never comes back to the site to start a new validation, or, there when the user does come back, but never starts a validation (just requests the first page). After hitting the start button, it either gets loaded anew (they opted in by checkbox) or gets removed if it exists from a previous session.

**Comment by poorgeek** [comment]
Ah ok. Thanks for the breakdown. Based on this, I'll hold off on creating that new issue to reflect the existence of the IndexedDB in the state of the checkbox. And then from a ux perspective, we should either hide or disable the new clear button if there is no local census data.

**Comment by LinuxBozo** [comment]
Not sure that it's entirely worth it to do that check. In order to check for the existence of a IndexedDB database, you are forced to do an `open()`. When you do this, it creates the db if it doesn't exist. So now, you have a database whether you wanted one or not, just to check if you should display a button to rid yourself of the database ;-)  Of course, you can then delete the database, and all that, and the database is empty, but at the added cost of this boilerplate overhead.

See: 
http://stackoverflow.com/questions/17468963/check-if-indexeddb-database-exists
http://stackoverflow.com/questions/23753014/check-existence-of-indexeddb-database
