### ISSUE TITLE
Progress bar intermittently extends beyond 100%

### ISSUE THREAD

**Issue by poorgeek** [cfpb/hmda-pilot#369]
Steps to reproduce:

1. Load a DAT file with more than 20k LAR (ex. lar_quality_errors_0002590037.dat)

Error: 
* Progress bar extends way past the edge of the modal window 
![progressbar-toolong](https://cloud.githubusercontent.com/assets/489299/7356023/e1931452-ece2-11e4-9d9e-9f7c66625cae.png)

Tested in
* Chrome Windows v39
* Chrome Mac v42

Tasks 
- [x] Cap the progress bar at 100%
- [x] Add an entry to the FAQ explaining the maxed out progress bar

**Comment by LinuxBozo** [comment]
The root cause here is a file that has a certain count of LARs defined in the transmittal sheet, but actually contains a different number of LARs in the file. In the case of `lar_quality_errors_0002590037.dat` the TS has the number at 12,354. The actual number of LARs in the file is 23,794. Since the progress bar completion estimate is based on the number in the TS (the only number we have at the start of processing the file), the bar is extended past 100% based on the "extra" LARs being present in the file.  So you can see why it looks like almost 200% complete based on these numbers. BTW, this situation is eventually caught by an edit, but not until the Quality edits are run ([Q130](https://github.com/cfpb/hmda-rule-spec/blob/master/2013/hmda-quality.json#L4)).

So we could fix this by just leaving the progress at 100% for the rest of the LARs being processed past what the TS has defined. This should not happen too often, but it may leave the user thinking that the application is "stuck" at 100%. The other option is to live with the extension past the point of 100% for this particular set of circumstances.

@lesgou @ericspry @feomike @vizui @poorgeek Thoughts?

**Comment by poorgeek** [comment]
A 3rd option would be to restart the progress bar at 0 once it extends past 100%. This isn't a great solution because no ones like a never ending progress bar, but it would show movement which may be better than having the progress bar capped at 100%. Of course, once it goes past 100% the first time, we have no way of knowing how far it will go after that. So it could go 0 to 100% back to 1% then Done.

I'd be curious as to why Q130 is a quality check at all and not at least a validity check? Is there a reason why it would be ok to submit a file with more or less LARs than is indicated in the transmittal sheet?

**Comment by vizui** [comment]
Could the green bar be shifted to the left (using CSS) if it goes beyond
100%? That way it still appears to still be approaching the end of the
progress meter.

**Comment by poorgeek** [comment]
@vizui I'm not sure what you're suggesting. I think you're suggesting one of two things:

* Reduce the progress bar length by some amount when it reaches 100% and let it count back up to 100%
* When the progress bar length reaches 100%, begin counting backwards to zero, then back up to 100% if gets to 0 until its done

Are either of those what you're suggesting?

I'd be wary of the first item because people hate that style of progress bar. The 2nd option is interesting and would be a little more difficult to implement, but at least it shows continuous movement.

**Comment by poorgeek** [comment]
per @ericspry this morning, we're going to cap the progress bar at 100% and an item to the FAQ on "why  does my progress bar stop at 100%?"

**Comment by ericspry** [comment]
Make it so. 
![image](https://cloud.githubusercontent.com/assets/2027141/7373111/aa3515ee-ed98-11e4-92e2-d59f23d38225.png)
