### ISSUE TITLE
Create FAQs for developer questions

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#374]
As a developer at a bank,
I would like a resource on the site that provides developer-level information regarding HMDA edits and explains how to use APIs available to bank developers

Tasks for this story:
- [x] Identify where on the HMDA Pilot site a developer will access the developer page
- ~~Design the layout of the developer page~~
- [x] Include links to file/edit specs
- [x] Include links to JSON specs
- [x] Include instructions on how to use the one LAR feature

**Comment by poorgeek** [comment]
Since this project is hosted on github, as a developer I would expect the documentation to live as a markdown file here rather than as a page with the site. We certainly could so something similar to what we did with the About or FAQ pages and include them in both places, but it might be better to keep the links on the site focused on the site functionality and developer documentation in github. We could also link to the developer docs from the FAQ with questions like "Does the HMDA Pilot have an open API?" and/or "Where can I find out more information about file edit specs you're using for validation?".

**Comment by ericspry** [comment]
I agree with @poorgeek  - the docs should be in MD on the git repo, and a link from the FAQ would probably also be useful.
