### ISSUE TITLE
View a high-level report of the quality/macro edit results

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#93]
Child of Epic #6 
As a user I want to be able to see an electronic report of the failures that have failed at a high level so that I am able to get an overall view of how many quality/macro edits I have failed and where I need to look deeper to find the LARs I need to correct

Acceptance Criteria
After I select the file to run the edits on and the edits are run in the background, a summary report displaying the names of the syntactical and validity edits that failed and the counts of the edits that failed, would be displayed.

If the syntactical and validity edits are clean and I move onto the quality/macro edit screen, the name of the quality and macro edits that have failed and the counts should be displayed. 

Acceptance Test
**Given** that the edits were run on my HMDA data filing
**When** I first receive my edit results
**Then** I would like to see an electronic report at a high level showing how many quality/macro edits failed

Tasks
- [x] Create wireframe for summary view @vizui
- [x] Display the list of Quality errors, if they exist
- [x] Display the list of Macro errors, if they exist
- [x] Display the File metadata
- [x] User can Continue to the MSA and IRS summary page if the user has verified and/or commented on every quality/macro edit error
- [x] User can go Back to the Syntactical and Validity summary page
- [x] Display whether the user has verified an error or not

**Comment by poorgeek** [comment]
How should we determine if the user can move on to the MSA/IRS page? Typically you would think that the user would have to verify all of the quality errors and verify/comment all of the macro errors, but since saving information from the user was determined to be a post-pilot story, we have no way of knowing if the user has performed the verify task for any of the quality/macro edits.

The simple solution would be to maintain a simple user object in memory that we could store data on for now. And if the user refreshes the browser, closes the tab, etc... that object would be wiped out along with anything that the engine is storing like the file JSON or any errors.

**Comment by debseidner** [comment]
@poorgeek I think when we talked about this in the past that the session the user is in was going to be stored but as you mention above, if the user closes the browser or refreshes the browser and cache gets cleared out, then the information that the user just entered wasn't going to be stored for pilot.

**Comment by ericspry** [comment]
Cool. As per sprint discussion, we'll go with @poorgeek proposed simple solution.

**Comment by poorgeek** [comment]
Blocking this story since the last task can not be completed until work progresses on #37 & #35.
